### ISSUE TITLE
Can't build schema using npm

### ISSUE THREAD

**Issue by ellisonbg** [vega/vega-lite#1380]
Please:
- [X] Check for duplicate issues
- [X] Describe how to reproduce the bug /  the goal of the new feature request
- [X] Provide an example spec and/or screenshots (if applicable) 

On a clean checkout of vega-lite in the `composition-interaction-prototype` branch, if I do `npm install` following by trying to build the schema I get the following error:

```
$ npm run schema

> vega-lite@1.0.8 schema /Users/bgranger/github/vega/vega-lite
> typescript-json-schema --required true src/spec.ts ExtendedSpec > vega-lite-schema.json

/Users/bgranger/github/vega/vega-lite/node_modules/typescript/lib/typescript.js:15712
            return symbol.parent ? getFullyQualifiedName(symbol.parent) + "." + symbolToString(symbol) : symbolToString(symbol);
                         ^

TypeError: Cannot read property 'parent' of null
    at Object.getFullyQualifiedName (/Users/bgranger/github/vega/vega-lite/node_modules/typescript/lib/typescript.js:15712:26)
    at JsonSchemaGenerator.getTypeDefinition (/Users/bgranger/github/vega/vega-lite/node_modules/typescript-json-schema/typescript-json-schema.js:315:35)
    at JsonSchemaGenerator.getDefinitionForProperty (/Users/bgranger/github/vega/vega-lite/node_modules/typescript-json-schema/typescript-json-schema.js:154:35)
    at /Users/bgranger/github/vega/vega-lite/node_modules/typescript-json-schema/typescript-json-schema.js:258:41
    at Array.reduce (native)
    at JsonSchemaGenerator.getClassDefinition (/Users/bgranger/github/vega/vega-lite/node_modules/typescript-json-schema/typescript-json-schema.js:256:49)
    at JsonSchemaGenerator.getTypeDefinition (/Users/bgranger/github/vega/vega-lite/node_modules/typescript-json-schema/typescript-json-schema.js:356:26)
    at JsonSchemaGenerator.getDefinitionForProperty (/Users/bgranger/github/vega/vega-lite/node_modules/typescript-json-schema/typescript-json-schema.js:154:35)
    at /Users/bgranger/github/vega/vega-lite/node_modules/typescript-json-schema/typescript-json-schema.js:258:41
    at Array.reduce (native)
```

**Comment by ellisonbg** [comment]
I should note that building the schema works fine on master.

**Comment by domoritz** [comment]
Yeah, this branch in pre-alpha and we only wanted to build the code. I have to look into this to see why the schema cannot be built.

**Comment by ellisonbg** [comment]
OK great.

On Sun, May 22, 2016 at 12:01 PM, Dominik Moritz <notifications@github.com>
wrote:

> Yeah, this branch in pre-alpha and we only wanted to build the code. I
> have to look into this to see why the schema cannot be built.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vega/vega-lite/issues/1380#issuecomment-220849574>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by kanitw** [comment]
FYI, we plan to reimplement feature in the branch rather than trying to merge directly as the code have greatly diverged so this is no longer an issue.
