### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1581]
Running` npm run build` shows this error:

```

Error: Cannot find module 'browserify-versionify' from '/Users/kanitw/Documents/_code/vega-lite/node_modules/datalib'
    at /Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
The code that you piped into exorcist contains no source map!
Therefore it was piped through as is and no external map file generated.
```

This might be related to #1575 

cc: @mathisonian

**Comment by mathisonian** [comment]
I think that error is bubbling up from datalib, it should go away once vega/datalib#81 is merged. Also related to vega/vega#369

**Comment by jheer** [comment]
vega/datalib#81 has been merged!
