### ISSUE TITLE
Test gallery not working

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1719]
```
Error: Cannot find module 'd3' from '/Users/kanitw/Documents/_code/vega-lite/test-gallery'
    at /Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/kanitw/Documents/_code/vega-lite/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by kanitw** [comment]
Note that I have tried running `npm install` inside `test-gallery`

**Comment by domoritz** [comment]
Hmm, I guess d3 should be a dev dependency. The test gallery does not have a separate package.json.

**Comment by domoritz** [comment]
Can't reproduce but I added d3 as a dev dependency.
