### ISSUE TITLE
graph draws fine in HTML output, but will not export to PNG using vl2png

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#1770]
You are totally within your rights to say "figure this out yourself", but it's the first time I've seen this particular problem.

Two source files are here, generated from Altair:
http://tinyurl.com/z4l2e2a

- HTML file `engines_topc_m_teps_drawsfine.html` (gzipped). This opens fine in numerous web browsers. It exports a PNG just fine.
- The JSON source that HTML file exports (`Vega_JSON_Source.json`, gzipped). 

(Note: Both files are, like, 60 MB when uncompressed. Sorry. Someday, https://github.com/altair-viz/altair/issues/183 will help out a lot here.)

When I export that JSON using vl2vg/vg2png, though, I get the following error, which I've never had before. Never had an Altair chart that drew an HTML chart just fine but then could not run vl2vg/vg2png on the output. Thought y'all might want to take a look.

```
undefined:1
{"mark": "point", "data": {"values": [{"sub_algorithm": null, "jsondir": null, "edges_redundance": null, "partition_method": null, "rmat_vmin": null, "size_check": null, "stream_from_host": null, "instrument": null, "compensate": null, "load_time": null, "undirected": null, "vertices_visited": 1139906.0, "gunrock_version": null, "total_time": null, "source_list": null, "per_iteration_advance_runtime": null, "destination_vertex": null, "traversal_mode": null, "elapsed": 855.187, "top_nodes": null, "debug_mode": null, "search_depth": null, "source_vertex": null, "64bit_VertexId": null, "compiler": null, "rgg_seed": null, "compiler_version": null, "num_gpus": null, "preprocess_time": null, "rgg_vmultipiler": null, "edges_queued": null, "max_queue_sizing1": null, "duplicate_graph": null, "rmat_edgefactor": null, "rmat_vmultipiler": null, "num_edges": null, "max_queue_sizing": null, "rgg_scale": null, "rmat_d": null, "rmat_c": null, "rmat_b": null, "rmat_a": null, "delta_factor": null, "rmat_scale":

SyntaxError: Unexpected token I
    at Object.parse (native)
    at /Users/jowens/Documents/working/vega-lite/bin/vl2vg:28:19
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
undefined:1



SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/jowens/Documents/working/vega/bin/vg2png:41:19
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by jowens** [comment]
I am fairly sure that the error will not show up in the files above, because someplace in the pipeline, something in the altair/vega chain has cleaned up this JSON. But, I think what is happening here is that the `I` in the syntax error above was caused by a line that looked like this:
`
"m_teps": Infinity
`
which I produced in my Pandas dataframe by dividing by zero (and this is exactly how Pandas will store it, I gather). Since `Infinity` is bare here, it's probably going to screw up your parser. I am not sure how you might detect and correct this, or even if it's your responsibility, but this is what's causing the error, I believe.
