### ISSUE TITLE
Layer Histogram doesn't render

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1828]
```
{
  "data": {"url": "data/flights-2k.json"},
  "layers": [
    {
      "mark": "bar",
      "encoding": {
        "x": {
          "field": "distance",
          "type": "quantitative",
          "bin": true
        },
        "y": {
          "aggregate": "count",
          "field": "*",
          "type": "quantitative"
        }
      }
    },
    {
      "transform": {"filter": "datum.delay < 5"},
      "mark": "bar",
      "encoding": {
        "x": {
          "field": "distance",
          "type": "quantitative",
          "bin": true
        },
        "y": {
          "aggregate": "count",
          "field": "*",
          "type": "quantitative"
        },
        "color": {"value": "goldenrod"}
      }
    }
  ]
}
```

We got the following error: 

```
Uncaught Error: Undefined data set name: undefined
    at error (http://localhost:1233/vendor/vega.js:806:9)
    at Subscope.prototype$71.getData (http://localhost:1233/vendor/vega.js:29076:5)
    at http://localhost:1233/vendor/vega.js:28209:22
    at Array.map (native)
    at numericMultipleDomain (http://localhost:1233/vendor/vega.js:28208:24)
    at multipleDomain (http://localhost:1233/vendor/vega.js:28145:29)
    at parseScaleDomain (http://localhost:1233/vendor/vega.js:28118:22)
    at parseScale (http://localhost:1233/vendor/vega.js:28074:13)
    at http://localhost:1233/vendor/vega.js:28670:5
    at Array.forEach (native)
```

The output seems to have weird domain for x-scale

```
{
          "name": "x",
          "type": "linear",
          "round": true,
          "nice": true,
          "zero": false,
          "range": [0,200],
          "domain": {
            "fields": [
              "bin_distance_start", // ??
              "bin_distance_end",
              {
                "data": "layer_1_summary",
                "fields": ["bin_distance_start","bin_distance_end"]
              }
            ]
          }
        },
```

So this is probably relevant to layer domain merge.

**Comment by domoritz** [comment]
Works now.
