### ISSUE TITLE
config.overlay.line  is not working

### ISSUE THREAD

**Issue by yhoonkim** [vega/vega-lite#2136]
```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v2.0.json",
    "data":{
      "values":[
        {
          "N1": "Bren1",
          "Q1": 3.167,
          "T1": "2017-02-02T12:35:15.000Z"
        },
        {
          "N1": "Bren2",
          "Q1": 4.167,
          "T1": "2017-02-02T12:35:15.000Z"
        },{
          "N1": "Bren2",
          "Q1": 3.167,
          "T1": "2017-02-03T12:35:15.000Z"
        },
        {
          "N1": "Bren1",
          "Q1": 4.167,
          "T1": "2017-02-03T12:35:15.000Z"
        }
      ]
    },
    "mark": "line",
    "encoding": {
      "column": {
        "field": "N1",
        "type": "nominal"
      },
      "y": {
        "bin": {},
        "field": "Q1",
        "type": "quantitative"
      },
      "x": {
        "timeUnit": "yearmonthdate",
        "field": "T1",
        "type": "temporal"
      }
    },
    "config": {
      "overlay": {
        "line": true
      }
    }
  }
```
This spec threw an error:
```
facet.ts:511 Uncaught TypeError: Cannot read property 'reduceFieldDef' of undefined
    at new TimeUnitNode (http://localhost:9002/node_modules/vega-lite/build/vega-lite.js:3706:30)
    at TimeUnitNode.clone (http://localhost:9002/node_modules/vega-lite/build/vega-lite.js:3720:24)
    at clone (http://localhost:9002/node_modules/vega-lite/build/vega-lite.js:2433:31)
    at Array.map (native)
    at clone (http://localhost:9002/node_modules/vega-lite/build/vega-lite.js:2445:46)
    at Array.map (native)
    at clone (http://localhost:9002/node_modules/vega-lite/build/vega-lite.js:2445:46)
    at Array.map (native)
    at clone (http://localhost:9002/node_modules/vega-lite/build/vega-lite.js:2438:46)
    at Array.map (native)
```
It is working when `config.overlay.line = false`.
(I found this after the merge @domoritz )

**Comment by kanitw** [comment]
@domoritz  this is the error I got, so this might be relevant to your PR:

```
Uncaught Error: Undefined data set name: "child_source"
    at error (http://localhost:1234/vendor/vega.js:686:9)
    at Scope.prototype$71.getData (http://localhost:1234/vendor/vega.js:30313:5)
    at analyze (http://localhost:1234/vendor/vega.js:29529:22)
    at parseData$1 (http://localhost:1234/vendor/vega.js:29504:36)
    at http://localhost:1234/vendor/vega.js:29900:5
    at Array.forEach (native)
    at parseSpec (http://localhost:1234/vendor/vega.js:29899:22)
    at parseView (http://localhost:1234/vendor/vega.js:29966:3)
    at Object.parse$2 [as parse] (http://localhost:1234/vendor/vega.js:30503:10)
    at Object.ved.parseVg (http://localhost:1234/app/editor.js:250:22)
```
