### ISSUE TITLE
Circular dependencies due to buildModel when importing Vega-Lite to Voyager

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2832]
```

      at Object.__extends (node_modules/vega-lite/node_modules/tslib/tslib.js:53:9)
      at node_modules/vega-lite/src/compile/baseconcat.ts:11:47
      at Object.<anonymous> (node_modules/vega-lite/src/compile/baseconcat.ts:11:1)
      at Object.<anonymous> (node_modules/vega-lite/src/compile/concat.ts:4:1)
      at Object.<anonymous> (node_modules/vega-lite/src/compile/common.ts:13:1)
      at Object.<anonymous> (node_modules/vega-lite/src/compile/layout/header.ts:8:1)
      at Object.<anonymous> (node_modules/vega-lite/src/compile/model.ts:34:1)
      at Object.<anonymous> (node_modules/vega-lite/src/compile/selection/selection.ts:13:1)
      at Object.<anonymous> (node_modules/vega-lite/src/filter.ts:3:1)
      at Object.<anonymous> (src/models/shelf/spec.ts:6:99)
      at Object.<anonymous> (src/models/shelf/index.ts:4:90)
      at Object.<anonymous> (src/models/index.ts:7:46)
      at Object.<anonymous> (src/selectors/index.test.ts:3:1)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:744:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

I'll rewrite buildModel to avoid circular dependencies.

**Comment by kanitw** [comment]
Somehow this only occurs when Voyager imports Vega-Lite, but causes no problem in Vega-Lite itself.
