### ISSUE TITLE
vl2vg should not have a hardcoded dependency within vega-lite distro

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#3598]
vl2vg used to be standalone (I could copy / link it to a ~/bin directory), but now it references other files within the vega-lite distro, which is unfortunate since now I can't move it / link it elsewhere.

```
Error: Cannot find module '../build/vega-lite'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jowens/Documents/working/vega-lite/bin/vl2vg:12:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by domoritz** [comment]
Thank you for looking into it.
