### ISSUE TITLE
yarn site throws an error

### ISSUE THREAD

**Issue by invokesus** [vega/vega-lite#3804]
Running `yarn site` on master errors out with the following message:-
```
> scripts/update-version.sh

module.js:663
    throw err;
    ^

SyntaxError: /Users/invokesus/vega-lite/_data/examples.json: Unexpected token } in JSON at position 13905
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:660:27)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/invokesus/vega-lite/scripts/create-example-pages:9:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by domoritz** [comment]
Can you look at examples.json and see what might be wrong?
