### ISSUE TITLE
vl2vg 3.0.0-rc0 cannot find module 'json-stringify-pretty-compact'

### ISSUE THREAD

**Issue by pepijnve** [vega/vega-lite#4104]
The `vl2vg` command in a fresh install of vega-lite 3.0.0-rc0 fails to run. See output below.

```
Cerris:~ pepijn$ npm install -g vega-lite
/usr/local/bin/vl2png -> /usr/local/lib/node_modules/vega-lite/bin/vl2png
/usr/local/bin/vl2svg -> /usr/local/lib/node_modules/vega-lite/bin/vl2svg
/usr/local/bin/vl2vg -> /usr/local/lib/node_modules/vega-lite/bin/vl2vg
+ vega-lite@3.0.0-rc0
added 1 package, removed 4 packages and updated 16 packages in 2.84s
Cerris:~ pepijn$ vl2vg
module.js:545
    throw err;
    ^

Error: Cannot find module 'json-stringify-pretty-compact'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vega-lite/bin/vl2vg:13:24)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by domoritz** [comment]
Thank you, we'll look into this.

**Comment by domoritz** [comment]
Hmm, `node bin/vl2vg examples/specs/bar.vl.json` works in master.

**Comment by domoritz** [comment]
`node node_modules/vega-lite/bin/vl2vg` does not when I install `vega-lite`.

**Comment by domoritz** [comment]
Ohh, it's because the compact stringify is only a dev dependency. Will fix.
