### ISSUE TITLE
Generation png with online example

### ISSUE THREAD

**Issue by sgaunet** [vega/vega-lite#5279]
Sorry, I'm probably doing something wrong but I'm not able to generate a png with the vg2png command line with a csv file.

I took the csv file seatltle-weather.csv and an online example except that I would like to do it in command line :

```
$ ls data/seattle-weather.csv
data/seattle-weather.csv
$ cat line.json
{
      "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
        "data": {"url": "data/seattle-weather.csv"},
          "mark": "line",
            "encoding": {
                    "x": {"timeUnit": "year", "field": "date", "type": "temporal"},
                        "y": {"aggregate": "mean", "field": "temp_max", "type": "quantitative"}
                      }
}

$ vg2png line.json toto.png
WARN Data ingestion failed data/seattle-weather.csv SyntaxError: Unexpected token d in JSON at position 0
    at JSON.parse (<anonymous>)
    at json (/usr/lib/node_modules/vega-cli/node_modules/vega-loader/build/vega-loader.node.js:296:17)
    at read (/usr/lib/node_modules/vega-cli/node_modules/vega-loader/build/vega-loader.node.js:364:10)
    at View.request (/usr/lib/node_modules/vega-cli/node_modules/vega-dataflow/build/vega-dataflow.js:829:16)
    at <anonymous>
```

What's wrong please ?

**Comment by domoritz** [comment]
Use `vl2png`. `vg2png` expects Vega.
