### ISSUE TITLE
Changes uncovered by Altair 4

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-lite#5595]
In https://github.com/altair-viz/altair/pull/1818 I begun the process of making Altair wrappers for Vega-Lite 4.0.0-beta.12. This introduced a couple test failures in examples due to properties that are no longer allowed by the schema.

## To add back

- [x] https://altair-viz.github.io/gallery/ridgeline_plot.html fails because ``bounds`` is no longer an allowed property of ``TopLevelUnitSpec``.
  - Ham: this one we should add back.
 

- [x] Any charts that use ``width`` or ``height`` in the view configuration break, because they are no longer allowed properties of ``ViewConfig``
  - Ham: this one we should add back, perhaps as deprecated configs.

## Need to decide whether we want to add these back

- [ ] https://altair-viz.github.io/gallery/anscombe_plot.html and several others fail because ``columns`` is no longer an allowed property of ``TopLevelUnitSpec``.

- [ ] https://altair-viz.github.io/gallery/beckers_barley_trellis_plot.html fails because ``rangeStep`` is no longer an allowed property of ``Scale``.

- [ ] Similarly, https://altair-viz.github.io/gallery/layered_chart_bar_mark.html fails because ``rangeStep`` is no longer an allowed property of ``ScaleConfig``

This is the extent of the issues that came up in a first pass!

**Comment by kanitw** [comment]
I'm adding `bounds` and `config.view.width/height` back in https://github.com/vega/vega-lite/pull/5624. 

However, I don't think we should do `columns` as it's much better to specify:  `alt.Facet('Series', columns=2)`.

**Comment by kanitw** [comment]
For `rangeStep`, width.step is also a much better syntax, so I slight prefer not to add it back.

**Comment by jakevdp** [comment]
Thanks!

**Comment by kanitw** [comment]
:)

**Comment by jakevdp** [comment]
One question: currently altair's default theme uses config.width/config.height. Would you prefer me to change that to config.continuousWidth/continuousHeight in V4, to move away from deprecated configs?

**Comment by kanitw** [comment]
Yes, please. :)

**Comment by jakevdp** [comment]
Great! Already done in https://github.com/altair-viz/altair/commit/0ccd2e4a8c59f9fa5a1009ed4716bd6882187d01

**Comment by eharkins** [comment]
Changing `scale.rangeStep` to `width.step` in Altair version 4.0.1 caused this for me:

```
Error: Unrecognized signal name: "x_step"
    at Object.error (/home/eharkins/miniconda2/envs/altairtest2/lib/vega-cli/node_modules/vega-util/build/vega-util.js:22:11)
    at Scope$1.prototype$1.getSignal (/home/eharkins/miniconda2/envs/altairtest2/lib/vega-cli/node_modules/vega-parser/build/vega-parser.js:3342:16)
    at /home/eharkins/miniconda2/envs/altairtest2/lib/vega-cli/node_modules/vega-parser/build/vega-parser.js:84:65
    at Array.forEach (<anonymous>)
    at parseExpression (/home/eharkins/miniconda2/envs/altairtest2/lib/vega-cli/node_modules/vega-parser/build/vega-parser.js:82:17)
    at Scope$1.prototype$1.parseLambdas (/home/eharkins/miniconda2/envs/altairtest2/lib/vega-cli/node_modules/vega-parser/build/vega-parser.js:3360:15)
    at parseSpec (/home/eharkins/miniconda2/envs/altairtest2/lib/vega-cli/node_modules/vega-parser/build/vega-parser.js:2972:11)
    at parseMark (/home/eharkins/miniconda2/envs/altairtest2/lib/vega-cli/node_modules/vega-parser/build/vega-parser.js:2136:13)
    at parseAxis (/home/eharkins/miniconda2/envs/altairtest2/lib/vega-cli/node_modules/vega-parser/build/vega-parser.js:2934:12)
    at /home/eharkins/miniconda2/envs/altairtest2/lib/vega-cli/node_modules/vega-parser/build/vega-parser.js:2960:44
```

**Comment by domoritz** [comment]
@eharkins Can you send us the Vega-Lite spec?

**Comment by eharkins** [comment]
@domoritz Here it is with `width.step`:

```
{
  "config": {
    "view": {
      "continuousWidth": 400,
      "continuousHeight": 300
    }
  },
  "layer": [
    {
      "data": {
        "name": "data-4289b732a1ecf6d27f9445f6f478c2e9"
      },
      "mark": {
        "type": "rect",
        "color": "grey",
        "opacity": 0.25
      },
      "encoding": {
        "x": {
          "type": "ordinal",
          "field": "x"
        }
      }
    },
    {
      "data": {
        "name": "data-76aa2d4335a13d734091ef8b4d7100db"
      },
      "mark": {
        "type": "tick",
        "opacity": 1,
        "thickness": 2
      },
      "encoding": {
        "color": {
          "type": "nominal",
          "field": "real_mut",
          "legend": null,
          "scale": {
            "domain": [
              true,
              false
            ],
            "range": [
              "black",
              "transparent"
            ]
          }
        },
        "x": {
          "type": "ordinal",
          "axis": {
            "grid": false
          },
          "field": "position",
          "scale": {
            "zero": true
          },
          "title": "position"
        },
        "y": {
          "type": "nominal",
          "axis": {
            "grid": true
          },
          "field": "seq_id",
          "scale": {
            "zero": true
          },
          "sort": [
            "944860330169026868",
            "-8009227471980910973"
          ],
          "title": "sequence"
        }
      },
      "title": "test lineage",
      "width": {
        "step": 3
      }
    }
  ],
  "background": "white",
  "$schema": "https://vega.github.io/schema/vega-lite/v4.0.2.json",
  "datasets": {
    "data-4289b732a1ecf6d27f9445f6f478c2e9": [
      {
        "x": 25
      },
      {
        "x": 26
      },
      {
        "x": 27
      },
      {
        "x": 28
      },
      {
        "x": 29
      },
      {
        "x": 30
      },
      {
        "x": 31
      },
      {
        "x": 32
      },
      {
        "x": 50
      },
      {
        "x": 51
      },
      {
        "x": 52
      },
      {
        "x": 53
      },
      {
        "x": 54
      },
      {
        "x": 55
      },
      {
        "x": 56
      },
      {
        "x": 57
      },
      {
        "x": 95
      },
      {
        "x": 96
      },
      {
        "x": 97
      },
      {
        "x": 98
      },
      {
        "x": 99
      },
      {
        "x": 100
      },
      {
        "x": 101
      },
      {
        "x": 102
      },
      {
        "x": 103
      },
      {
        "x": 104
      },
      {
        "x": 105
      },
      {
        "x": 106
      },
      {
        "x": 107
      },
      {
        "x": 108
      },
      {
        "x": 109
      },
      {
        "x": 110
      },
      {
        "x": 111
      }
    ],
    "data-76aa2d4335a13d734091ef8b4d7100db": [
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 0,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 1,
        "mut_from": "A",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 2,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 3,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 4,
        "mut_from": "T",
        "mut_to": "T",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 5,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 6,
        "mut_from": "T",
        "mut_to": "T",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 7,
        "mut_from": "A",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 8,
        "mut_from": "A",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 9,
        "mut_from": "C",
        "mut_to": "C",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 10,
        "mut_from": "T",
        "mut_to": "T",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 11,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 12,
        "mut_from": "A",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 13,
        "mut_from": "T",
        "mut_to": "T",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 14,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 15,
        "mut_from": "A",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 16,
        "mut_from": "A",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 17,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "naive",
        "index": 0,
        "seq_id": 944860330169026800,
        "position": 18,
        "mut_from": "T",
        "mut_to": "T",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 0,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 1,
        "mut_from": "A",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 2,
        "mut_from": "G",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": true
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 3,
        "mut_from": "G",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": true
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 4,
        "mut_from": "T",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": true
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 5,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 6,
        "mut_from": "T",
        "mut_to": "C",
        "region": "Framework",
        "radical": true,
        "real_mut": true
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 7,
        "mut_from": "A",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 8,
        "mut_from": "A",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 9,
        "mut_from": "C",
        "mut_to": "C",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 10,
        "mut_from": "T",
        "mut_to": "T",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 11,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 12,
        "mut_from": "A",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": true
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 13,
        "mut_from": "T",
        "mut_to": "T",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 14,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 15,
        "mut_from": "A",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": true
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 16,
        "mut_from": "A",
        "mut_to": "A",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 17,
        "mut_from": "G",
        "mut_to": "G",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      },
      {
        "type": "lineage_member",
        "index": 1,
        "seq_id": -8009227471980911000,
        "position": 18,
        "mut_from": "T",
        "mut_to": "T",
        "region": "Framework",
        "radical": false,
        "real_mut": false
      }
    ]
  }
}
```

**Comment by domoritz** [comment]
Can you create a minimal example that shows the issue?

**Comment by eharkins** [comment]
Yes @domoritz I'll try stripping things down until it's as bare of an altair chart as possible that still gets the error with `width.step`. Thanks for your response!

**Comment by eharkins** [comment]
@domoritz I updated the above spec to a minimal example. I'm almost positive that it's because I added `width.step` to one sub layer of the chart and then added it to another chart in altair using `+` in python. If I move `width.step` to the top level LayerChart resulting from the `+`, the error goes away.

So maybe it's just a matter of adding a helpful message for `width.step` like this one for `chart.background`:
```
ValueError: Objects with "background" attribute cannot be used within LayerChart. Consider defining the background attribute in the LayerChart object instead.
```

**Comment by domoritz** [comment]
I don't get an error in the Vega editor [try me](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjKCFIDdkBTAd023FzzngBdl4BXWRgZwHVkATWgC3IAsABiEAaSlRgJ6TFqwASRNL1rkAzCIlgAvpW3i8AGwCGATyIAncgG0tOKlC7Hax8vYdR4xgLZFykJxcAWgAjAFYuAA4AJgA2AE5I41jjRDCARkRIoQB2DUic43iuWMRY6CEYyC0IfRqob2MLAGt-CyJoVQMHSCJ4OC4GdCx3HoAPN3rJWlMABz8sSFgLQa9DSG6PPBQiQy5-Camdet0qOqpRvEDXEaPIL19-a9DoSKJ4+LCE9M-YriIuNAuNEBLEwmpEDkcrFMjlImpqh5zj1Gi1-PRoK1Nrhev1YKthhQtlAJrdiXgZvN-MtVsZ1tiPJAdnt-LNYKxkPQEIitqcHMjJCRuHxJsTIKxaERZuoTlo+QBdbqQAAkrGgvCIjX8Klos1YGAA9Ab8ERUMYAHSoTm8Rghc3IWAGtUaxrG03GIKGTlEY0Cc0AK1Y3KV11YRForFFOOe4SicUSyVSGSyuXyhWKpXKlWiNnqlxxQnIQllVEVWgCzg9IVe71+8R+X3+gOBoPBkOhsPhuY8+bwbI5XPgRZLuHlehA2iAA). Could it be that the issue is fixed in the latest VL version?

**Comment by eharkins** [comment]
Yes it could be. [It seems like](https://github.com/altair-viz/altair/commit/7a446a5f85a50800d6e490e44e8fde04f6d96cdf) Altair 4.0.1 is using VegaLite 4.0.2 and there have been subsequent releases of VegaLite so perhaps one of those contains a fix for this.

**Comment by jakevdp** [comment]
The current release of Altair uses Vega-Lite 4.0.2, so it's possible that errors won't reproduce in the Vega editor (which I believe is at 4.4 at the moment)
