### ISSUE TITLE
Using vl2png (and etc bin tools) via npx

### ISSUE THREAD

**Issue by nbevans** [vega/vega-lite#6983]
```
C:\Sandbox\Nodetest>npx vl2png --help
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/vl2png - Not found
npm ERR! 404
npm ERR! 404  'vl2png@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Is vl2png et al meant to be recognised by npx as valid aliases? The VL docs suggest they should be.

**Comment by domoritz** [comment]
The vl2png commands are part of Vgea-Lite so you need to tell npx the package. `npx -p vega-lite vl2png --help`.

However, there seems to be a problem where `vega-cli` is not a direct requirement. I will fix that.

**Comment by domoritz** [comment]
Actually, this works: `npx -p vega -p vega-lite vl2png --help`.

**Comment by nbevans** [comment]
That works! Thank you! I will confess that NodeJS is all a bit foreign to me so please forgive me if it seems like an amateur problem to have encountered.

**Comment by domoritz** [comment]
Thanks for reporting the issue. There was definitely a lack of documentation. https://github.com/vega/vega-lite/pull/6984 will address the lack.

**Comment by sterlingpetersen** [comment]
This doesn't seem to be working using a spec. Any workarounds? Wish I knew npx better...

```
npx -p vega -p vega-lite vl2pdf ~/Desktop/simpleBarChart.vl.json > ~/Desktop/simpleBarChart.pdf     
Error: CanvasRenderer is missing a valid canvas or context
    at Object.error (/Users/sterlingpetersen/.npm/_npx/13c2d0f208089529/node_modules/vega-util/build/vega-util.js:39:11)
    at CanvasRenderer.resize (/Users/sterlingpetersen/.npm/_npx/13c2d0f208089529/node_modules/vega-scenegraph/build/vega-scenegraph.js:3633:28)
    at CanvasRenderer.initialize (/Users/sterlingpetersen/.npm/_npx/13c2d0f208089529/node_modules/vega-scenegraph/build/vega-scenegraph.js:3190:19)
    at CanvasRenderer.initialize (/Users/sterlingpetersen/.npm/_npx/13c2d0f208089529/node_modules/vega-scenegraph/build/vega-scenegraph.js:3621:30)
    at initializeRenderer (/Users/sterlingpetersen/.npm/_npx/13c2d0f208089529/node_modules/vega-view/build/vega-view.js:643:14)
    at renderHeadless (/Users/sterlingpetersen/.npm/_npx/13c2d0f208089529/node_modules/vega-view/build/vega-view.js:762:12)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async View.renderToCanvas [as toCanvas] (/Users/sterlingpetersen/.npm/_npx/13c2d0f208089529/node_modules/vega-view/build/vega-view.js:798:15)
```

**Comment by sterlingpetersen** [comment]
This seems to work. Thanks!

```
npx -p vega-cli -p vega-lite vl2pdf ~/Desktop/simpleBarChart.vl.json > ~/Desktop/simpleBarChart.pdf
```
