### ISSUE TITLE
current build failure on clean pull of master branch

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#715]
```$ npm run build

> vega-lite@0.8.3 build /Users/jowens/Documents/working/vega-lite
> gulp build

[10:17:02] Using gulpfile ~/Documents/working/vega-lite/gulpfile.js
[10:17:02] Starting 'schema'...
Warning: gulp-run is deprecated
[10:17:02] Finished 'schema' after 16 ms
[10:17:02] Starting 'build'...
[10:17:02] Finished 'build' after 114 ms
$ node # Silenced
module.js:339
    throw err;
    ^

Error: Cannot find module '../../lib/json3-compactstringify.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at [stdin]:4:11
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:435:26)
    at node.js:578:27
    at doNTCallback0 (node.js:419:9)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Command `node` exited with code 1
    at ChildProcess.<anonymous> (/Users/jowens/Documents/working/vega-lite/node_modules/gulp-run/lib/command.js:145:15)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

npm ERR! Darwin 15.0.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "run" "build"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE
npm ERR! vega-lite@0.8.3 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vega-lite@0.8.3 build script 'gulp build'.
npm ERR! This is most likely a problem with the vega-lite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls vega-lite
npm ERR! There is likely additional logging output above.```

**Comment by kanitw** [comment]
@jowens  Thanks for reporting.  I made a bad cherry-pick, but it should work now.
