### ISSUE TITLE
vl2png:  CanvasRenderer is missing a valid canvas or context

### ISSUE THREAD

**Issue by aborruso** [vega/vega-lite#7450]
Hi,
starting from this [config file](https://gist.githubusercontent.com/aborruso/85554d674bfa4a6fd62df1d2eca01b3d/raw/08b5900cb5629fef60eb31a3d9f6e00566c18193/vl_trellis.json) and running

```
vl2png vl_trellis.json out.png
```

I have

```
WARN The step for "height" is dropped because the y is continuous.
Error: CanvasRenderer is missing a valid canvas or context
    at Object.error (/home/aborruso/n/lib/node_modules/vega/node_modules/vega-util/build/vega-util.js:39:11)
    at CanvasRenderer.resize (/home/aborruso/n/lib/node_modules/vega/node_modules/vega-scenegraph/build/vega-scenegraph.js:3635:28)
    at CanvasRenderer.initialize (/home/aborruso/n/lib/node_modules/vega/node_modules/vega-scenegraph/build/vega-scenegraph.js:3192:19)
    at CanvasRenderer.initialize (/home/aborruso/n/lib/node_modules/vega/node_modules/vega-scenegraph/build/vega-scenegraph.js:3623:32)
    at initializeRenderer (/home/aborruso/n/lib/node_modules/vega/node_modules/vega-view/build/vega-view.js:672:14)
    at renderHeadless (/home/aborruso/n/lib/node_modules/vega/node_modules/vega-view/build/vega-view.js:791:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async View.renderToCanvas [as toCanvas] (/home/aborruso/n/lib/node_modules/vega/node_modules/vega-view/build/vega-view.js:827:15)
```

How to solve it?

**Comment by aborruso** [comment]
> Make sure to try a sunken bar chart. I think the node canvas module is missing.

Thank you @domoritz , but why a JSON that [works in the editor](https://vega.github.io/editor/?#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQspAjhoQmAE5xBwiAH0mSLYLgBPRSAAmcaFpo5M7eegAqOvTQhXnmM2igmHAAHpgaAJKyZDoQEDQABLRsWirCcA4JNLIJbhlIODRICVHBsvHExQAUbhEAlAnFUHIAZlpymGwJzTkOzaSZnZhIwlk5tVbNgikaAMQAjABsABwAwqsA7FYtHQDKNABe6qjzy0pIsrAz6BDDWuFKO7Lh6ACyHRAZWkgPIBDMfgC6AAMilEFk8AwEAlrGxploEvFMI01JgFN05J8oMFMAwEUhrI5vFBsmQEro6JQEgA5VQY2SVLwQcmyGjQpBQBJtUk0PTFFpwBi0H5Wf5MQFwABiHQ072eny033CAF8lNYfihUKA8YINFhcPgiLRbtQ6IwmAwFT0yphKM0EAQkEwUlpLRwxIsAJxMMQAZl9SE9Yms8xaSGWcEW8ygvqYcA2ABZlknFkhfVAoARvgB3Ahxz2LJhxxYbYyB+ZwJjzDZwKAAJiYLQTnvmCagYjrAYTcAADHAE-MxJ6CNpdPo7RBiCBVSBkFoANYaHBsbK-eA0MhYQJ-YI4NDzOszuCXNiE6LbsNQOAvUAtGi6awaWyyNgIbJIA4uOAGHTJWTqJRMHMHBjhAFIzxGSY4Shco0F9QC6CBEBpyUEIL3vQRH3QUlYniAxgm+QokAMVdjwqFBAOA0CAEcGAuPwfhoUhfEQ0CohiOx4iSdhUhGe9MmyXIIlFKARmOUAjnaNAw0ET4lBwAkzzIfce2VGdLC1EA7wfDQCIKIoSOeMimIozQqI0Wj6LoRjmIQ-xQLcNhhjMBI+jYAZEkEiYlGgMTt0kthpJGOSQAU6wlJUtTALYOFnD3VAAG1bwwrDZzsACzJAjQXzfNIWPsjQ1E+acAF0lCma5kp09AioyoCsvQHL311JQzDIY8sKCVjZTsGhpyikBYjhZjNN8oFQDQ7DZFsEDpuPX4NJAbIZo6+b+uVIA) does not work in this cli?

**Comment by domoritz** [comment]
The browser has a native canvas implementation while node does not.

**Comment by aborruso** [comment]
> The browser has a native canvas implementation while node does not.

What about to add `canvas` when checking installation requirements, during `npm install -g vega-lite` procedure?

**Comment by domoritz** [comment]
If you install `vega-cli`, you'll get it by default. Try installing `npm install -g vega-lite vega-cli`.
