### ISSUE TITLE
"TypeError: Cannot read property 'max' of undefined"

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#777]
Lemme know if you want input.

```/Users/jowens/Documents/working/vega-lite/vega-lite.js:5240
    return d3_format.format(format)(fieldStats.max).length;
                                              ^

TypeError: Cannot read property 'max' of undefined
    at getMaxNumberLength (/Users/jowens/Documents/working/vega-lite/vega-lite.js:5240:47)
    at getMaxLength (/Users/jowens/Documents/working/vega-lite/vega-lite.js:5248:16)
    at /Users/jowens/Documents/working/vega-lite/vega-lite.js:5272:29
    at Array.forEach (native)
    at offset (/Users/jowens/Documents/working/vega-lite/vega-lite.js:5263:32)
    at Object.default_1 [as default] (/Users/jowens/Documents/working/vega-lite/vega-lite.js:5181:14)
    at Object.compile (/Users/jowens/Documents/working/vega-lite/vega-lite.js:4752:34)
    at compile (/Users/jowens/Documents/working/vega-lite/bin/vl2vg:53:20)
    at /Users/jowens/Documents/working/vega-lite/bin/vl2vg:48:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
/Users/jowens/Documents/working/vega-lite/vega-lite.js:5240
    return d3_format.format(format)(fieldStats.max).length;
                                              ^```

**Comment by kanitw** [comment]
> Lemme know if you want input.

Yep.  We always want an input to reproduce the bug  :)

**Comment by jowens** [comment]
https://gist.github.com/jowens/6a633a80b6516e44a72c

**Comment by kanitw** [comment]
Assuming you are using latest master -- changing `name` => `field` is working in my computer.

**Comment by jowens** [comment]
Exactly. Fixed. Thanks @kanitw.
