### ISSUE TITLE
"TypeError: properties[mark] is not a function" (vega-lite and vega, current master)

### ISSUE THREAD

**Issue by jowens** [vega/vega-lite#844]
```TypeError: properties[mark] is not a function
    at Object.compileMarks (/Users/jowens/Documents/working/vega-lite/vega-lite.js:2991:41)
    at Object.compile (/Users/jowens/Documents/working/vega-lite/vega-lite.js:2152:25)
    at compile (/Users/jowens/Documents/working/vega-lite/bin/vl2vg:33:20)
    at /Users/jowens/Documents/working/vega-lite/bin/vl2vg:29:3
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)```

```{"marktype": "bar", "data": {"values": [{"m_teps": 33.5330810546875, "dataset": "ak2010"}, {"m_teps": 21.458358764648438, "dataset": "belgium_osm"}, {"m_teps": 1023.6077880859375, "dataset": "cit-Patents"}, {"m_teps": 502.16387939453125, "dataset": "coAuthorsDBLP"}, {"m_teps": 10.410270690917969, "dataset": "delaunay_n13"}, {"m_teps": 187.35877990722656, "dataset": "delaunay_n21"}, {"m_teps": 443.1048889160156, "dataset": "delaunay_n24"}, {"m_teps": 55.096927642822266, "dataset": "europe_osm"}, {"m_teps": 3530.5595703125, "dataset": "kron_g500-logn21"}, {"m_teps": 79.42512512207031, "dataset": "road_usa"}, {"m_teps": 2050.32421875, "dataset": "soc-LiveJournal1"}]}, "encoding": {"y": {"field": "m_teps", "scale": {"type": "log"}, "type": "Q", "axis": {"title": "MTEPS"}}, "x": {"field": "dataset", "type": "O"}}}```

**Comment by kanitw** [comment]
We renamed `marktype` => `mark`.  Please look at 0.9.0's release log for other potential things that might affect you.  

https://github.com/vega/vega-lite/releases/tag/v0.9.0

**Comment by kanitw** [comment]
I just tested - changing to just `mark` this would work now.  

Btw, it is recommended to use marktype "point" for log scale as "length" could mislead the true value of each item.

**Comment by jowens** [comment]
Sorry for the issue. My bad. I'm assuming you mean "mark=point" instead of "mark=bar", but maybe "length" means "bar". Points look good though! I like points. Thanks for the protip.

**Comment by kanitw** [comment]
Ah yes,  Use "point" over "bar" for log scale :)

**Comment by kanitw** [comment]
Thank you for helping us find bugs :)
