### ISSUE TITLE
"not in PATH env variable" when saving from altair

### ISSUE THREAD

**Issue by aborruso** [vega/vega-lite#8566]
Hi,
if I run this code

```python
import pandas as pd
import altair as alt

df = pd.read_csv("tmp.csv",keep_default_na=False)

df['year'] = pd.to_datetime(df['year'], format='%Y')

chart=alt.Chart(df).mark_area().encode(
    alt.X('year:T', timeUnit = 'year',title='year',axis=alt.Axis(tickCount='year')),
    alt.Y('v:Q',axis=alt.Axis(format='%'),title='percentage'),
    color='i:N'
)
```

I have no errors, I have the chart.

If I add `chart.save('tmp/chart.png')`

I have these errors:

```
(not in PATH env variable)
/usr/local/lib/node_modules/vega-lite/build/vega-lite.js:740
      deepMerge_(dest, s ?? {});
                          ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vega-lite/bin/vl2vg:6:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

I found similar errors here, but i don't understand how to apply them to my case.
Does anyone have any suggestions?

I'm using altair 4.2.0

Thank you

**Comment by domoritz** [comment]
What's your node version? `node --version`?

**Comment by aborruso** [comment]
> What's your node version? `node --version`?

v12.22.12

Thank you

**Comment by aborruso** [comment]
@domoritz do you have any advice for me?

Thank you

**Comment by domoritz** [comment]
Node 12 is no longer supported: https://endoflife.date/nodejs. Update your node version.

**Comment by aborruso** [comment]
> Node 12 is no longer supported: https://endoflife.date/nodejs. Update your node version.

Thank you

**Comment by domoritz** [comment]
Make sure to install `vega-cli`, not just `vega`.  See https://vega.github.io/vega-lite/usage/compile.html#cli

**Comment by domoritz** [comment]
This works for me btw

```
echo '{"data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"}, "mark": "point"}' | npx -p vega-lite vl2vg | npx -p vega-cli vg2png >o.png
```

**Comment by aborruso** [comment]
> This works for me btw
> 
> ```
> echo '{"data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"}, "mark": "point"}' | npx -p vega-lite vl2vg | npx -p vega-cli vg2png >o.png
> ```

I have this error

```
Error: CanvasRenderer is missing a valid canvas or context
    at Object.error (/home/aborruso/.npm/_npx/1c2a57d892d95236/node_modules/vega-util/build/vega-util.js:39:11)
    at CanvasRenderer.resize (/home/aborruso/.npm/_npx/1c2a57d892d95236/node_modules/vega-scenegraph/build/vega-scenegraph.js:5291:28)
    at CanvasRenderer.initialize (/home/aborruso/.npm/_npx/1c2a57d892d95236/node_modules/vega-scenegraph/build/vega-scenegraph.js:4852:19)
    at CanvasRenderer.initialize (/home/aborruso/.npm/_npx/1c2a57d892d95236/node_modules/vega-scenegraph/build/vega-scenegraph.js:5279:32)
    at initializeRenderer (/home/aborruso/.npm/_npx/1c2a57d892d95236/node_modules/vega-view/build/vega-view.js:683:14)
    at renderHeadless (/home/aborruso/.npm/_npx/1c2a57d892d95236/node_modules/vega-view/build/vega-view.js:802:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async View.renderToCanvas [as toCanvas] (/home/aborruso/.npm/_npx/1c2a57d892d95236/node_modules/vega-view/build/vega-view.js:838:15)
```

**Comment by aborruso** [comment]
> This works for me btw
> 
> ```
> echo '{"data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"}, "mark": "point"}' | npx -p vega-lite vl2vg | npx -p vega-cli vg2png >o.png
> ```

The first part works. I have no error running

```
echo '{"data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"}, "mark": "point"}' | npx -p vega-lite vl2vg
```

**Comment by domoritz** [comment]
Huh, strange. I have 

```
> npx --version
9.2.0
> node --version
v19.2.0
```

on macOS.

**Comment by aborruso** [comment]
I have npx 9.2.0 and node v16.18.1  :(

**Comment by domoritz** [comment]
I feel those should still work. What happens if you install `vega-cli`? Do you see any errors?

**Comment by aborruso** [comment]
> I feel those should still work. What happens if you install `vega-cli`? Do you see any errors?

If I run `npm install -g vega-cli` I have

```
added 118 packages, and changed 17 packages in 10s

8 packages are looking for funding
  run `npm fund` for details
```

**Comment by domoritz** [comment]
Huh, that looks good. Maybe try removing your node modules and try again. This doesn't look like an issue with Vega, though.

**Comment by aborruso** [comment]
> Huh, that looks good. Maybe try removing your node modules and try again. This doesn't look like an issue with Vega, though.

I take advantage of your great kindness and preparation. To do it at it's best the command is simply `npm uninstall -g  vega-lite vega-cli canvas vega`?

Is there a better way to do it?

Thank you

**Comment by aborruso** [comment]
@domoritz I can't solve. For the things I have to do, I think I can solve it with https://github.com/vega/vl-convert
