### ISSUE TITLE
Error: "Cannot read properties of undefined (reading '0')" from histogram when providing a default value to a linked scatterplot

### ISSUE THREAD

**Issue by NateLanza** [vega/vega-lite#9390]
## Bug Description
I've been attempting to create a visualization in `react-vega` that links a histogram to a scatterplot with an interval selection brush and accepts default values for the brush. I've noticed that, when a default value is provided to the scatterplot, the histogram generates an error `Cannot read properties of undefined (reading '0')` (no error is generated for two linked scatterplots). In react, this manifests as no lines rendering in the histogram. In the vega editor, the histogram instead does not update when the selection is cleared (the pink line should only appear when a selection is active): [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5LiUOScxoA2qBj3Zjl6ADuNZfRoAEwADCFK8DRkWMFhSsjaANZooJgAnjhw+jhsNLJONiA4pkgIEN4gsqVZ6EzaDBAwiiAQcIJwUE6aIOmZ+nmYcNrESHpKUO2m+ghsDXDKbD7WtqMMNaAAHi4AzGHhACx7ALpKaS6h4bshR1ZWJyBwnmzKeWQpIFvdAGY0bcr6AHU4FEsAB9PKgwRMcpKXo1EAARwYSHydDUNFIzWgo3WIAAXkM2GgvqNWrCMvDhLI4FNbqd3j8-voACI0CA4QRIKCIR5Ocl9dBIlGYNEizFKbHtd4E7RE1AkwRknoU-RUmnaEB0kD2QRsDXdDwvEVyd7FbSlfR1BpNJSIHDpYmkuArQRrfQAYjg2wA7N6oEFNbc7jY3B4vKhXCA-AEmqgLhFgdEuvGQJy0kMKphzbIIF89QgKspHhA6Gd0Kz2ZzuQheZqFKATIIoAxOYN9KpMAwEM4ADogEauuB9o7NJDlctsjlcnn5TX3M2lceRqo1y31RpYtodLqpFXoAZDAfNR72F6yMhLj4ge4TdXTWatBZLQP3BLJdBq49PM9vbqfUCMoI-wTpW041rO-LwkKqLqGKWSwnQUogVO1a1oUZYAb8QHtsWpbNHC+jQSKsEYvBPSIfCOCykwSBMDQeGFGwxRQHhBpyEa7DyBGoALgWtTrjaDwIPaZYKkqA5uqgACMdwupJISUPsQb1j02a5vmFQ-IIgz6jxJR8SAVobnSoBFjmrEgBWKEzgUKmNs2rbwh2Xa9v2qxDteo7jpZk5VjZc7xKY76pnkZEns8rzvP+ICAcBPmgahEHKgKiLIjB6LiuRmBIfF1ngbZIAYTFWFxWZJYOpBhFpcRGVkcROVUWwNF0cIFUtI2uILMgeQuOEClSTchQ6nq7wSfCno+n6AaMcxrGgGNaAybcNwrVYQA). This vega chart appears perfectly correct when you load it but clicking the scatterplot once immediately creates the bug.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {"url": "data/cars.json"},
  "vconcat": [
    {
        "hconcat": [
            {
                "width": 200,
                "height": 200,
                "mark": {
                    "type": "point"
                },
                "params": [
                    {
                        "name": "brush",
                        "select": {
                            "type": "interval",
                            "clear": "mousedown"
                        },
                        "value": {
                            "x": [3000, 4000],
                            "y": [200, 300]
                        }
                    }
                ],
                "encoding": {
                    "x": {
                        "field": "Weight_in_lbs",
                        "type": "quantitative",
                        "scale": {
                            "zero": false,
                            "type": "linear"
                        }
                    },
                    "y": {
                        "field": "Displacement",
                        "type": "quantitative",
                        "scale": {
                            "zero": false,
                            "type": "linear"
                        }
                    },
                    "color": {
                        "condition": {
                            "param": "brush",
                            "empty": false,
                            "value": "#e377c2"
                        }
                    }
                }
            }
        ]
    },
    {
        "hconcat": [
            {
                "width": 200,
                "height": 200,
                "layer": [
                    {
                        "transform": [
                            {
                                "density": "Displacement"
                            },
                            {
                                "calculate": "datum[\"value\"]",
                                "as": "Displacement"
                            }
                        ],
                        "params": [
                            {
                                "name": "brush",
                                "select": {
                                    "type": "interval",
                                    "encodings": [
                                        "x"
                                    ],
                                    "clear": "mousedown"
                                }
                            }
                        ],
                        "mark": "line",
                        "encoding": {
                            "x": {
                                "field": "Displacement",
                                "type": "quantitative",
                                "title": "Displacement"
                            },
                            "y": {
                                "field": "density",
                                "type": "quantitative",
                                "title": "probabiity"
                            },
                            "opacity": {
                                "condition": [
                                    {
                                        "param": "brush",
                                        "empty": false,
                                        "value": 1
                                    }
                                ],
                                "value": 0.4
                            }
                        }
                    },
                    {
                        "transform": [
                            {
                                "filter": {
                                    "param": "brush"
                                }
                            },
                            {
                                "density": "Displacement"
                            },
                            {
                                "calculate": "datum[\"value\"]",
                                "as": "Displacement"
                            }
                        ],
                        "mark": "line",
                        "encoding": {
                            "x": {
                                "field": "Displacement",
                                "type": "quantitative",
                                "title": "Displacement"
                            },
                            "y": {
                                "field": "density",
                                "type": "quantitative",
                                "title": "probability",
                                "scale": {"domain": [0, 0.1]}
                            },
                            "color": {"value": "#e377c2"},
                            "opacity": {
                                "value": 1
                            }
                        }
                    }
                ]
            }
        ]
    }
]
}
```

You'll note that, when dragging a new selection, the histogram bugs out with tons of errors: `Cannot read properties of undefined (reading 'marktype')`. This appears to be caused by `encoding.color` on the histogram. Before entirely narrowing down this minimal example, I produced this error on [this chart](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5LiUOScxoA2qBj3Zjl6ADuNZfRoAEwADCFK8DRkWMFhSsjaANZooJgAnjhw+jhsNLJONiA4pkgIEN4gsqVZ6EzaDBAwiiAQcIJwUE6aIOmZ+nmYcNrESHpKUO2m+ghsDXDKbD7WtqMMNaAAHi4AzGHhACx7ALpKaS6h4bshR1ZWJyBwnmzKeWQpIFvdAGY0bcr6AHU4FEsAB9PKgwRMcpKXo1EAARwYSHydDUNFIzWgo3WIAAXkM2GgvqNWrCMvDhLI4FNbqd3j8-voACI0CA4QRIKCIR5Ocl9dBIlGYNEizFKbHtd4E7RE1AkwRknoU-RUmnaEB0kD2QRsDXdDwvEVyd7FbSlfR1BpNJSIHDpYmkuArQRrfQAYjg2wA7N6oEFNbc7jY3B4vKhXCA-AEmqgLhFgdEuvGQJy0kMKphzbIIF89QgKspHhA6Gd0Kz2ZzuQhec0yLKGDgmGXnC1mK0+dq2LqNTcFKATIIoAxOYN9KpMAwEM4ADogEauuBzo7NJDlctsjlcnn5TX3M2ldeRqo1y31RpYtodLqpFXoAZDBfNR72F6yMhHj4ge4TdXTWatAsSyBvcCTJOgarPk8b5vN0nygIygj-BulbbjWu78vCQqouoYpZLCdBSihW7VrWhRlghvxIeOxals0cL6NhIq4Ri+E9IR8I4LKTBIEwNB0YUbDFFAdEGnIRrsPIEagAeBa1OeNoPAg9plgqSoLm6qAAIx3C6mkhJQ+xBv2PTZrm+YVD8giDPqMklHJIBWhedKgEWOaiSAFYkTuBQmYOw6jvCE5TrO86rEu36ruunmblWPl7vEpjgameRsS+zyvO88EgIhyExahpEYcqAqIsiOHouK7GYER+XeehvkgBROVUXlbklg6mGMWVzEVWxzE1VxbA8XxdESoOuILMgeQuOEBlaTchQ6nqDItfoEDtnAnbtGQjzIbII6CGNOLvNmO0rUy6BLRqxkgEJXKiaAGk1Dptw3G94xyD8sHALcQA) without the `marktype` error. The only difference is `encoding.color` on the histogram, which is set to an object related to my dataset that shouldn't work as well in the vega editor, but somehow works better. In this example, no selection line is displayed on the second histogram due to the color being incorrect, but it does produce the titular error message with no additional errors. I'm not sure whether this difference in behavior between the two is a second bug that deserves its own issue.

## Checklist

- [x] I checked for duplicate issues.

**Comment by NateLanza** [comment]
If it helps, the stacktrace in React:
```
TypeError: Cannot read properties of undefined (reading '0')
    at Object.eval (eval at Fd (vega-runtime.module.js:88:14), <anonymous>:3:102)
    at Ot._update (vega-dataflow.module.js:965:19)
    at Ot.evaluate (vega-dataflow.module.js:576:20)
    at Ot.run (vega-dataflow.module.js:601:17)
    at ij.Nue [as evaluate] (vega-dataflow.module.js:1525:17)
    at ij.evaluate (vega-view.module.js:1087:39)
    at ij.Due [as run] (vega-dataflow.module.js:1633:48)
    at Vega.js:46:23
    at VegaEmbed.js:36:13
```
Per the debugger, this comes from the following anonymous function, which I assume is `eval`'d:
```
var datum=event.item&&event.item.datum;
return [this.scale("concat_1_concat_0_x",_["$brush_AvgRating"][0]),this.scale("concat_1_concat_0_x",_["$brush_AvgRating"][1])]; 
```
Let me know if a separate issue in `react-vega` would be helpful.

**Comment by NateLanza** [comment]
[Here's](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5LiUOScxoA2qBj3Zjl6ADuNZfRoAEwADCFK8DRkWMFhSsjaANZooJgAnjhw+jhsNLJONiA4pkgIEN4gsqVZ6EzaDBAwiiAQcIJwUE6aIOmZ+nmYcNrESHpKUO2m+ghsDXDKbD7WtqMMNaAAHi4AzGHhACx7ALpKaS6h4bshR1ZWJyBwnmzKeWQpIFvdAGY0bcr6AHU4FEsAB9PKgwRMcpKXo1EAARwYSHydDUNFIzWgo3WIAAXkM2GgvqNWrCMvDhLI4FNbqd3j8-voACI0CA4QRIKCIR5Ocl9dBIlGYNEizFKbHtd4E7RE1AkwRknoU-RUmnaEB0kD2QRsDXdDwvEVyd7FbSlfR1BpNJSIHDpYmkuArQRrfQAYjg2wA7N6oEFNbc7jY3B4vKhXCA-AEmqgLhFgdEuvGQJy0kMKphzbIIF89QgKspHhA6Gd0Kz2ZzuQheZr7mbSuUI6AqjXLfVGli2h0uqkVegBkMRmMHk8XrIyE3nB8QPcJurprNWgsloH7glkug1c1HvZx29up9QIzBP90MO3fz4ULUeoxVlYXQpeW2RyuTz8pr6d9fqf9EWc1LZo4X0G8RTvDEHx6J94RwWUmCQJgaCAwo2GKKAgINOQjXYeRmyKEoC1qDsbQeBB7TLBUlQvGoAEY7hdN1UBCSh9iDBRUmzXN8wqH5BEGfVQAbIiQCtTs6VAACSwdF9K3fGtPwYkAN1VPIoN3Z5XneI8QBPM8QBo4D+0RZFb3RcVoMwZ8QArN9q1rQoy2PX99KkoCr1A0zwPMqDwOsuC2AQpDhAdCUTGfSS2GQPIXHCFjaJuQodT1d5DPQT0fT9ANUPQzDQDS+jbhuYqrCAA) a slightly simpler version where the issue still occurs; I've removed the calculation to rename "value" to the name of the field in the density plot. I wanted the signal to include the name of the field being brushed over because my application listens to signals & saves brush values externally, but this issues still occurs without the calculation.

I've also noticed that removing the `params` field entirely from the histogram solves this issue, as seen [here](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5LiUOScxoA2qBj3Zjl6ADuNZfRoAEwADCFK8DRkWMFhSsjaANZooJgAnjhw+jhsNLJONiA4pkgIEN4gsqVZ6EzaDBAwiiAQcIJwUE6aIOmZ+nmYcNrESHpKUO2m+ghsDXDKbD7WtqMMNaAAHi4AzGHhACx7ALpKaS6h4bshR1ZWJyBwnmzKeWQpIFvdAGY0bcr6AHU4FEsAB9PKgwRMcpKXo1EAARwYSHydDUNFIzWgo3WIAAXkM2GgvqNWrCMvDhLI4FNbqd3j8-voACI0CA4QRIKCIR5Ocl9dBIlGYNEizFKbHtd4E7RE1AkwRknoU-RUmnaEB0kD2QRsDXdDwvEVyd7FbSlfR1BpNJSIHDpYmkuArQRrfQAYjg2wA7N6oEFNbc7jY3B4vKhXCA-AEmqgLhFgdEuvGQJy0kMKphzbIIF89QgKspHhA6Gd0Kz2ZzuQheZr7glkug1c1HvYXrI3t1PqBGYJ-ugRq6svz4ULUeoxcOenQpeW2RyuTz8pr6d9fn39EWc6XmnD9GORROMVPD7OirKmEgmDQd4U2MUoDuDXIjex5BHQGaLbV6o0Wwh7TLBUlUHN1UAARjuF0wJCSh9iDBRUmzXN8wqH5BEGfVPxKAsf2tQNEJUYsnxACsF2rWsoJABtVTyKdW2eV53m7EBe37EBQJPFVBWRcd0XFadMDPMiqyXApVx7dd2K3EsHRHfdeMPfiTxneEcAvK8aGEOSWhMWdQAWZA8hccJYPAm5Ch1PV3k4j0vV9f0VxAe8uSfUBbIgoMbm8qwgA). However, since I want the selection to go both ways, this doesn't really solve my issue. It appears that the density calculation in general doesn't work well with linking selections to other plots.
